'use strict';
const input=document.querySelector('#search'),results=document.querySelector('#results'),list=document.querySelector('#result-list'),count=document.querySelector('#result-count'),clear=document.querySelector('#clear');
const entries=[...document.querySelectorAll('.answer')].map(el=>({id:el.id,title:el.querySelector('summary').textContent,section:el.closest('section').querySelector('h2').textContent,body:el.querySelector('.body').textContent,aliases:el.dataset.keywords||''}));
function search(){const q=input.value.trim();results.hidden=!q;clear.hidden=!q;list.replaceChildren();if(!q)return;const matches=HubSearch.rank(entries,q);count.textContent=matches.length?`Znalezione odpowiedzi: ${matches.length}`:'Nie znaleziono odpowiedzi. Spróbuj krócej: „raport”, „wyjazd” lub „logowanie”. Możesz też wybrać obszar poniżej.';for(const e of matches){const a=document.createElement('a');a.href='#'+e.id;a.textContent=e.title;const small=document.createElement('small');small.textContent=e.section;a.append(small);list.append(a)}}
input.addEventListener('input',search);clear.addEventListener('click',()=>{input.value='';search();input.focus()});input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';search()}});
function reveal(id,{focus=false,scroll=true}={}){const el=document.getElementById(id);if(!el)return;if(el.matches('details'))el.open=true;const target=el.matches('details')?el.querySelector('summary'):el;if(focus){if(!el.matches('details'))target.setAttribute('tabindex','-1');target.focus({preventScroll:true})}if(scroll)requestAnimationFrame(()=>el.scrollIntoView({block:'start',behavior:'instant'}))}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;e.preventDefault();const id=decodeURIComponent(a.hash.slice(1));history.pushState(null,'','#'+encodeURIComponent(id));reveal(id,{focus:true})});
window.addEventListener('hashchange',()=>reveal(decodeURIComponent(location.hash.slice(1))));window.addEventListener('popstate',()=>reveal(decodeURIComponent(location.hash.slice(1))));if(location.hash)reveal(decodeURIComponent(location.hash.slice(1)));
document.querySelector('#copy-message').addEventListener('click',async()=>{const field=document.querySelector('#message-template'),status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText(field.value);status.textContent='Schemat skopiowany. Wklej go do WhatsApp i uzupełnij.'}catch{field.focus();field.select();status.textContent='Zaznaczono schemat. Skopiuj tekst ręcznie.'}});
let noticeTimer;document.addEventListener('click',async e=>{const button=e.target.closest('[data-copy]');if(!button)return;const url=new URL(location.href);url.hash=button.dataset.copy;try{await navigator.clipboard.writeText(url.href);const notice=document.querySelector('#link-status');notice.textContent='Link do odpowiedzi skopiowany.';clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.textContent='',3500)}catch{const box=document.querySelector('#link-fallback'),field=document.querySelector('#link-value');box.hidden=false;field.value=url.href;field.focus();field.select()}});document.querySelector('#close-link').addEventListener('click',()=>{document.querySelector('#link-fallback').hidden=true;document.querySelector('.menu-link').focus()});
